### ISSUE TITLE
rostopic: unable to echo subtopic/field

### ISSUE THREAD

**Issue by bgromov** [ros/ros_comm#200]
There is particular case when `rostopic echo` does not work:

```
$ rostopic echo /lwa_jtcart_controller/state/x
WARNING: no messages received and simulated time is active.
Is /clock being published?
```

where `state` is of type `robot_mechanism_controllers/JTCartesianControllerState` (see definition [here](http://www.ros.org/doc/api/robot_mechanism_controllers/html/msg/JTCartesianControllerState.html)). The `state` itself and all its fields are echoed without a problem. Also there is no problem of subscribing to `/lwa_jtcart_controller/state` and getting `x` in the C++ code.

The list of topics advertised/subscribed by [JTCartesianController](http://www.ros.org/wiki/robot_mechanism_controllers/JTCartesian%20Controller):

```
/lwa_jtcart_controller/command_pose
/lwa_jtcart_controller/command_posture
/lwa_jtcart_controller/gains
/lwa_jtcart_controller/state
/lwa_jtcart_controller/state/x_desi
```

**Comment by tfoote** [comment]
Are you sure that this is a problem with rostopic echo? It looks like your running in a simulator and the simulator is paused.  If that's the case they topic may not be being published.  

Please provide a way to reproduce the error.

**Comment by bgromov** [comment]
Hmm, I am not sure if it is a bug or missing functionality in rostopic/roscore(?), but that happens after a node trying to subscribe to 'subtopic' as to a normal topic, e.g. as RViz does.

So to reproduce it:
1. `rostopic pub /jtcart_controller_state robot_mechanism_controllers/JTCartesianControllerState <double-tab here for default message>`
2. Run RViz and add `rviz/Pose` display.
3. Set `/jtcart_controller_state/x` for the `Topic`.
4. Close RViz.
5. `rostopic echo /jtcart_controller_state/x`

Now, the last one will not produce any output.

P.S. Also, as I understand, there is no way to distinguish between 'subtopics' and topics from `rostopic` command line. So if I would additionally have a normal topic `/jtcart_controller_state/x` there will be no way to echo the `x` field of `/jtcart_controller_state`.

**Comment by tfoote** [comment]
I get this from rostopic echo:

```
tfoote@BigFoote:~$ rostopic echo /test/pose/position/x
1.0
---
^Ctfoote@BigFoote:~$ rostopic echo /test
header:
  seq: 3
  stamp:
    secs: 0
    nsecs: 0
  frame_id: ''
pose:
  position:
    x: 1.0
    y: 0.0
    z: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 0.0
---

```

Whle running this in rostopic pub

```
$ rostopic pub /test geometry_msgs/PoseStamped "header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: ''
pose:
  position:
    x: 1.0
    y: 0.0
    z: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 0.0"

```

This works before and after running rviz.
