### ISSUE TITLE
rostopic pub -f does not substitute times or headers

### ISSUE THREAD

**Issue by pierrefranklin** [ros/ros_comm#2308]
rostopic pub time and header substitution does not work with yaml file messages. For example:

```
rostopic pub -s -r 10 /test sensor_msgs/Temperature -f msg.yaml
```
with ```msg.yaml``` as
```
header:
  seq: 0
  stamp: now
  frame_id: ''
temperature: 0.0
variance: 0.0
```
results in a fixed timestamp.

In comparision,
```
rostopic pub -s -r 10 /test sensor_msgs/Temperature "header:
  seq: 0
  stamp: now
  frame_id: ''
temperature: 0.0
variance: 0.0"
```
updates the timestamp correctly.

Tested on Ubuntu 18.04, ros melodic.
